// NOTE: This code is auto-generated by `teraslice-cli assets registry`
// any manual changes will be lost next time this gets auto-generated.

import FaultyProcessor from '../src/faulty_processor/processor';
import FaultyProcessorSchema from '../src/faulty_processor/schema';

import FaultySlicerFetcher from '../src/faulty_slicer/fetcher';
import FaultySlicerSchema from '../src/faulty_slicer/schema';
import FaultySlicerSlicer from '../src/faulty_slicer/slicer';

export const ASSETS = {
    faulty_processor: {
        Processor: FaultyProcessor,
        Schema: FaultyProcessorSchema,
    },
    faulty_slicer: {
        Fetcher: FaultySlicerFetcher,
        Schema: FaultySlicerSchema,
        Slicer: FaultySlicerSlicer,
    },
};
